[
project
]
name = "pdf_rag"
version = "0.1.0"
description = "pdf_rag using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.83.0,<1.0.0",
    "streamlit>=1.32.0",
    "PyPDF2>=3.0.0",
    "watchdog>=4.0.0",
    "python-dotenv>=1.0.0"
]

[
project.scripts
]
pdf_rag = "pdf_rag.main:run"
run_crew = "pdf_rag.main:run"
streamlit_app = "pdf_rag.streamlit_app:main"

[
build-system
]
requires = ["hatchling"]
build-backend = "hatchling.build"
